// Generated by scripts/scrape-jv-properties.ts
// Last updated: 2026-07-16
// Source: https://jv-inmobiliaria.com

export interface JVProperty {
  title: string;
  price: string;
  location: string;
  address: string;
  type: "alquiler" | "venta" | "desarrollo";
  ambientes?: number;
  dormitorios?: number;
  banios?: number;
  description: string;
  url: string;
  image: string;
  propertyType: string;
}

export const JV_PROPERTIES: JVProperty[] = [
  {
    "title": "Casa Un Dormitorio con Cochera - Alquiler",
    "price": "$450.000 /por mes",
    "location": "Reconquista",
    "address": "Calle 42 número 2315, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Casa en barrio Center con las siguientes comodidades: un dormitorio; cocina comedor con mesada, bajo mesada y alacena; ba...",
    "url": "https://jv-inmobiliaria.com/propiedades/casa/reconquista/casa-un-dormitorio-con-cochera-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/07/13dc1b24-bcea-41b1-96f6-44e39d915598-scaled.jpeg",
    "propertyType": "Casa / Dúplex"
  },
  {
    "title": "Local Comercial Amplio en esquina a Estrenar! - Alquiler",
    "price": "$1.500.000",
    "location": "Reconquista",
    "address": "Jorge Newbery 798, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "banios": 1,
    "description": "Local comercial en edificio recientemente estrenado, sobre calle Newbery esquina Belgrano, que cuenta con una superficie ...",
    "url": "https://jv-inmobiliaria.com/propiedades/local/reconquista/local-comercial-amplio-en-esquina-a-estrenar-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/07/da9029e1-9a61-41da-a1aa-f52e0a4810af.jpeg",
    "propertyType": "Local"
  },
  {
    "title": "Dúplex 3 Dormitorios dentro de los Bvs c/Cochera - Alquiler",
    "price": "$950.000 /por mes",
    "location": "Reconquista",
    "address": "San Lorenzo 46, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 4,
    "dormitorios": 3,
    "banios": 2,
    "description": "Dúplex dentro de los bulevares con las siguientes comodidades: P/B: estar comedor amplio; cocina con mesada, bajo mesada,...",
    "url": "https://jv-inmobiliaria.com/propiedades/casa/reconquista/duplex-3-dormitorios-dentro-de-los-bvs-c-cochera-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/07/bce5c2e1-4515-4100-b224-09c694a0dbc1-scaled.jpeg",
    "propertyType": "Casa / Dúplex"
  },
  {
    "title": "Departamento 2 Dormitorios barrio Hospital - Alquiler $350.000!",
    "price": "$350.000 /por mes",
    "location": "Reconquista",
    "address": "27 de Abril 1418, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 3,
    "dormitorios": 2,
    "banios": 1,
    "description": "Departamento en barrio Hospital con las siguientes comodidades: P/B: living comedor; cocina con mesada, bajo mesada y ala...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-2-dormitorios-barrio-hospital-alquiler-350-000/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/07/275e2bdb-ed9e-4a00-8dcf-ec96177d373b.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Dpto 2 Dormitorios dentro de los Bvs. Con Cochera - Alquiler",
    "price": "$650.000 /por mes",
    "location": "Reconquista",
    "address": "Ituzaingó 1616, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 3,
    "dormitorios": 2,
    "banios": 1,
    "description": "Departamento dentro de los boulevares con las siguientes comodidades: dos dormitorios (uno con A/A); cocina con mesada, b...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-2-dormitorios-dentro-de-los-bvs-con-cochera-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/07/ffe1449f-b3cc-433c-9151-71e62d04ed0b-scaled.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Dpto Un Dormitorio en barrio Parque - Alquiler",
    "price": "$450.000 /por mes",
    "location": "Reconquista",
    "address": "Mitre 1828, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento en barrio Parque con las siguientes comodidades: un dormitorio con ventilador de techo, balcón; cocina comed...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-un-dormitorio-en-barrio-parque-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/07/99aa402e-3dfa-4bd1-a47a-a9bf5af81da5.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Departamento 2 Dormitorios a Estrenar !",
    "price": "$700.000 /por mes",
    "location": "Reconquista",
    "address": "Jorge Newbery & General Belgrano, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 3,
    "dormitorios": 2,
    "banios": 1,
    "description": "Departamento cerca del centro de Reconquista, que cuenta con las siguientes comodidades: 2 dormitorios con placard; cocin...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-2-dormitorios-a-estrenar/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/06/51403c5f-1e54-4900-af2a-0d08ce2d60d1-scaled.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Departamento Un Dormitorio dentro de los Bvs",
    "price": "$430.000 /por mes",
    "location": "Reconquista",
    "address": "Amenabar 1556, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento dentro de los bulevares con las siguientes comodidades: cocina comedor con mesada, bajo mesada, alacena, art...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-un-dormitorio-dentro-de-los-bvs/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/06/ae435f2a-1c3c-4a09-b83d-f2d458f8ab83.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Departamento Semi Amoblado Céntrico Un Dormitorio - Alquiler",
    "price": "$500.000 /por mes",
    "location": "Reconquista",
    "address": "Mitre & Bolívar, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento céntrico con las siguientes comodidades: un dormitorio con placard y A/A; cocina comedor con mesada, bajo me...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-semi-amoblado-centrico-un-dormitorio-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/06/bfb9f212-d58e-44e4-9ff4-b5d60043b4fb.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Casa 3 Dormitorios dentro de los Bulevares - Alquiler",
    "price": "Consultar",
    "location": "Reconquista",
    "address": "Almafuerte 786, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 4,
    "dormitorios": 3,
    "banios": 2,
    "description": "Casa dentro de los bulevares con las siguientes comodidades: P/B: estar/comedor con ventilador de techo; cocina con mesad...",
    "url": "https://jv-inmobiliaria.com/propiedades/casa/reconquista/casa-3-dormitorios-dentro-de-los-bulevares-alquiler-2/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/06/b0b5f543-fdcf-4df4-9df4-2e7d98615b45.jpeg",
    "propertyType": "Casa / Dúplex"
  },
  {
    "title": "Casa 3 Dormitorios dentro de los Bulevares - Alquiler",
    "price": "$1.300.000 /por mes",
    "location": "Reconquista",
    "address": "Sarmiento 575, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 4,
    "dormitorios": 3,
    "banios": 2,
    "description": "Casa dentro de los bulevares con las siguientes comodidades: P/B: cochera para dos autos; living comedor (con ventilador ...",
    "url": "https://jv-inmobiliaria.com/propiedades/casa/reconquista/casa-3-dormitorios-dentro-de-los-bulevares-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/06/793df9bd-668b-4b43-93fe-7179d931e8af.jpeg",
    "propertyType": "Casa / Dúplex"
  },
  {
    "title": "Local Comercial en Villa Ocampo - Alquiler",
    "price": "$650.000 /por mes",
    "location": "Villa Ocampo",
    "address": "Rivadavia 1480, Villa Ocampo, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 1,
    "banios": 1,
    "description": "Local comercial en Villa Ocampo con las siguientes comodidades: salón de 31,45 m2; baño; kitchen; frente vidriado. Sobre ...",
    "url": "https://jv-inmobiliaria.com/propiedades/local/villa-ocampo/local-comercial-en-villa-ocampo-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/06/c3723a8e-4f48-4bb9-a3b3-c9fbb835b5f0.jpeg",
    "propertyType": "Local"
  },
  {
    "title": "Local Comercial Céntrico en Villa Ocampo",
    "price": "$800.000 /por mes",
    "location": "Villa Ocampo",
    "address": "Rivadavia 1486, Villa Ocampo, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 1,
    "banios": 1,
    "description": "Local comercial en Villa Ocampo con las siguientes comodidades: Salón amplio de 52 M2; baño; frente vidriado. Sobre calle...",
    "url": "https://jv-inmobiliaria.com/propiedades/local/villa-ocampo/local-comercial-centrico-en-villa-ocampo/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/06/c29d02ac-c688-44a3-b9b3-0198db790966.jpeg",
    "propertyType": "Local"
  },
  {
    "title": "Departamento Un Dormitorio dentro de los Bvs c/ Cochera - Alquiler",
    "price": "Consultar",
    "location": "Reconquista",
    "address": "Almafuerte 566, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento dentro de los bulevares con las siguientes comodidades: un dormitorio en P/A; baño; P/B: cocina comedor con ...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-un-dormitorio-dentro-de-los-bvs-c-cochera-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/06/f6c389a7-644e-4cd8-a972-c7c881b82c69.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Dpto un Dormitorio dentro de los Bulevares - Alquiler",
    "price": "$450.000 /por mes",
    "location": "Reconquista",
    "address": "Colón 129, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento dentro de los bulevares con las siguientes comodidades: un dormitorio; cocina comedor con mesada, bajo mesad...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-un-dormitorio-dentro-de-los-bulevares-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/05/6b7dd88a-ca03-4b42-8562-d1c5f18c45b7.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Dpto un Dormitorio dentro de los Bulevares - Alquiler",
    "price": "$280.000 /por mes",
    "location": "Reconquista",
    "address": "General Belgrano 91, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento dentro de los bulevares con las siguientes comodidades: un dormitorio; cocina comedor con mesada y bajo mesa...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/4440/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/05/ea359c83-3f83-4dad-a1c4-d67710e4980c.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Departamento un Dormitorio en barrio Obligado - Alquiler $260.000.",
    "price": "$260.000 /por mes",
    "location": "Reconquista",
    "address": "Profesor Roselli número 920, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento en alquiler en barrio Obligado con las siguientes comodidades: un dormitorio; cocina comedor con mesada, baj...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-un-dormitorio-en-barrio-obligado-alquiler-260-000/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/05/ef055331-6f7e-4458-b4d2-9ce6ecaf5ee9.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Dpto 2 Dormitorios Céntrico semi amoblado - Alquiler",
    "price": "$590.000 /por mes",
    "location": "Reconquista",
    "address": "Mitre & Bolívar, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 3,
    "dormitorios": 2,
    "banios": 1,
    "description": "Departamento semi amoblado con las siguientes comodidades: dos dormitorios con placares (uno con A/A y el otro con ventil...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-2-dormitorios-centrico-semi-amoblado-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/05/e82505f9-11e6-466f-adf0-1ee64ea4bcec.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Local Comercial sobre calle Rossi",
    "price": "$400.000 /por mes",
    "location": "Reconquista",
    "address": "Instituto Superior de Profesorado N°4 \"Ángel Cárcano\", Calle Fray Antonio Rossi, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 1,
    "banios": 1,
    "description": "Local comercial en esquina: ambiente de 40 m2 aproximados, baño, kitchen. Ventanas vidriadas y rejas. Sobre calle Rossi e...",
    "url": "https://jv-inmobiliaria.com/propiedades/local/reconquista/local-comercial-sobre-calle-rossi/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/05/a0b6cbac-5816-4c82-8a4a-5299dace2fd4.jpeg",
    "propertyType": "Local"
  },
  {
    "title": "Local Comercial en barrio Chapero - Alquiler",
    "price": "$350.000 /por mes",
    "location": "Reconquista",
    "address": "Fuerza Aérea 268, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "banios": 1,
    "description": "Local comercial con las siguientes disposiciones: dos ambientes; frente vidriado y con rejas; baño. Mucha iluminación nat...",
    "url": "https://jv-inmobiliaria.com/propiedades/local/reconquista/local-comercial-en-barrio-chapero-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/05/c231a198-e7b8-4b3b-babd-e7d97f42cc1f-scaled.jpeg",
    "propertyType": "Local"
  },
  {
    "title": "Casa 3 Dormitorios Exclusiva Zona Residencial - Alquiler",
    "price": "$1.000.000 /por mes",
    "location": "Reconquista",
    "address": "Bolívar 512, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 4,
    "dormitorios": 3,
    "banios": 2,
    "description": "Casa en alquiler en exclusiva zona residencial con las siguientes comodidades: P/B: estar; living comedor; cocina amplia ...",
    "url": "https://jv-inmobiliaria.com/propiedades/casa/reconquista/casa-3-dormitorios-exclusiva-zona-residencial-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/04/4f0d2caf-cba0-4ae1-9c09-e217bd56e04d.jpeg",
    "propertyType": "Casa / Dúplex"
  },
  {
    "title": "Dpto dentro de lo Bulevares Un Dormitorio - Precio $200.000!",
    "price": "$200.000 /por mes",
    "location": "Reconquista",
    "address": "Almafuerte 1475, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento dentro de los bulevares con las siguientes comodidades: cocina comedor con mesada y bajo mesada; un dormitor...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-dentro-de-lo-bulevares-un-dormitorio-precio-300-000/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/03/3dcabdab-491c-4cf6-bc48-0e34998d8999.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Departamento Dos Dormitorios dentro de los Bulevares - Alquiler",
    "price": "$400.000 /por mes",
    "location": "Reconquista",
    "address": "Alvear 1126, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 2,
    "banios": 1,
    "description": "Departamento dentro de los bulevares con las siguientes comodidades: dos dormitorios con ventilador de techo; cocina con ...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-un-dormitorio-dentro-de-los-bulevares-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/03/4aa2b71d-b155-4300-b8f3-df7117821ff7.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Departamento Amoblado Un Dormitorio barrio Nazareth - Alquiler",
    "price": "$550.000 /por mes",
    "location": "Reconquista",
    "address": "Calle 34 número 4234, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento en barrio Nazareth con las siguientes comodidades: un dormitorio con dos camas, placares, ventilador de tech...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-amoblado-un-dormitorio-barrio-nazareth-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/01/4050987d-6119-483d-8fdb-63b32e2b794d.jpeg",
    "propertyType": "Departamento"
  },
  {
    "title": "Dúplex 2 Dormitorios Exclusivo en barrio Chapero - Alquiler",
    "price": "$1.150.000 /por mes",
    "location": "Reconquista",
    "address": "Pasaje 45-47 número 839, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 3,
    "dormitorios": 2,
    "banios": 2,
    "description": "Dúplex en barrio Chapero que cuenta con las siguientes comodidades: P/B: cochera; living comedor amplio; baño; cocina con...",
    "url": "https://jv-inmobiliaria.com/propiedades/casa/reconquista/duplex-2-dormitorios-exclusivo-en-barrio-chapero-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2026/01/89eff1ad-0fbe-4ba2-97d8-7da35216d6fb.jpeg",
    "propertyType": "Casa / Dúplex"
  },
  {
    "title": "Quinta Don Francisco - Alquiler por día!!",
    "price": "Consultar",
    "location": "Reconquista",
    "address": "Calle Fray Antonio Rossi 2807, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 4,
    "dormitorios": 2,
    "banios": 3,
    "description": "🏡QUINTA DON FRANCISCOUn lugar de encuentro 📍Zona Country La Rural, Rqta, Santa Fe. La casa tiene capacidad para ...",
    "url": "https://jv-inmobiliaria.com/propiedades/casa-quinta/reconquista/quinta-don-francisco-alquiler-por-dia/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2025/11/e79fd4d0-9fbc-48f3-a58c-35ce9fc1a4a1.jpeg",
    "propertyType": "Casa Quinta"
  },
  {
    "title": "Dpto un Dormitorio barrio Chapero - Alquiler",
    "price": "$300.000 /por mes",
    "location": "Reconquista",
    "address": "Calle 41 número 680, Reconquista, Santa Fe, Argentina",
    "type": "alquiler",
    "ambientes": 2,
    "dormitorios": 1,
    "banios": 1,
    "description": "Departamento en barrio Chapero con las siguientes comodidades: un dormitorio; cocina comedor con mesada y bajo mesada; ba...",
    "url": "https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-un-dormitorio-barrio-chapero-alquiler/",
    "image": "https://jv-inmobiliaria.com/wp-content/uploads/2025/11/IMG_3659-scaled.jpeg",
    "propertyType": "Departamento"
  }
];

export const JV_PROPERTIES_TEXT = `
=== PROPIEDADES ACTUALES DE JV DESARROLLOS INMOBILIARIOS ===

ALQUILER:
1. Casa Un Dormitorio con Cochera - Alquiler — $450.000 /por mes
   Ubicación: Reconquista
   Tipo: Casa / Dúplex
   2 ambientes, 1 dorm, 1 baños
   Casa en barrio Center con las siguientes comodidades: un dormitorio; cocina comedor con mesada, bajo mesada y alacena; ba...
   Link: https://jv-inmobiliaria.com/propiedades/casa/reconquista/casa-un-dormitorio-con-cochera-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/07/13dc1b24-bcea-41b1-96f6-44e39d915598-scaled.jpeg

2. Local Comercial Amplio en esquina a Estrenar! - Alquiler — $1.500.000
   Ubicación: Reconquista
   Tipo: Local
   2 ambientes, 1 baños
   Local comercial en edificio recientemente estrenado, sobre calle Newbery esquina Belgrano, que cuenta con una superficie ...
   Link: https://jv-inmobiliaria.com/propiedades/local/reconquista/local-comercial-amplio-en-esquina-a-estrenar-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/07/da9029e1-9a61-41da-a1aa-f52e0a4810af.jpeg

3. Dúplex 3 Dormitorios dentro de los Bvs c/Cochera - Alquiler — $950.000 /por mes
   Ubicación: Reconquista
   Tipo: Casa / Dúplex
   4 ambientes, 3 dorm, 2 baños
   Dúplex dentro de los bulevares con las siguientes comodidades: P/B: estar comedor amplio; cocina con mesada, bajo mesada,...
   Link: https://jv-inmobiliaria.com/propiedades/casa/reconquista/duplex-3-dormitorios-dentro-de-los-bvs-c-cochera-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/07/bce5c2e1-4515-4100-b224-09c694a0dbc1-scaled.jpeg

4. Departamento 2 Dormitorios barrio Hospital - Alquiler $350.000! — $350.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   3 ambientes, 2 dorm, 1 baños
   Departamento en barrio Hospital con las siguientes comodidades: P/B: living comedor; cocina con mesada, bajo mesada y ala...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-2-dormitorios-barrio-hospital-alquiler-350-000/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/07/275e2bdb-ed9e-4a00-8dcf-ec96177d373b.jpeg

5. Dpto 2 Dormitorios dentro de los Bvs. Con Cochera - Alquiler — $650.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   3 ambientes, 2 dorm, 1 baños
   Departamento dentro de los boulevares con las siguientes comodidades: dos dormitorios (uno con A/A); cocina con mesada, b...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-2-dormitorios-dentro-de-los-bvs-con-cochera-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/07/ffe1449f-b3cc-433c-9151-71e62d04ed0b-scaled.jpeg

6. Dpto Un Dormitorio en barrio Parque - Alquiler — $450.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento en barrio Parque con las siguientes comodidades: un dormitorio con ventilador de techo, balcón; cocina comed...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-un-dormitorio-en-barrio-parque-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/07/99aa402e-3dfa-4bd1-a47a-a9bf5af81da5.jpeg

7. Departamento 2 Dormitorios a Estrenar ! — $700.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   3 ambientes, 2 dorm, 1 baños
   Departamento cerca del centro de Reconquista, que cuenta con las siguientes comodidades: 2 dormitorios con placard; cocin...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-2-dormitorios-a-estrenar/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/06/51403c5f-1e54-4900-af2a-0d08ce2d60d1-scaled.jpeg

8. Departamento Un Dormitorio dentro de los Bvs — $430.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento dentro de los bulevares con las siguientes comodidades: cocina comedor con mesada, bajo mesada, alacena, art...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-un-dormitorio-dentro-de-los-bvs/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/06/ae435f2a-1c3c-4a09-b83d-f2d458f8ab83.jpeg

9. Departamento Semi Amoblado Céntrico Un Dormitorio - Alquiler — $500.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento céntrico con las siguientes comodidades: un dormitorio con placard y A/A; cocina comedor con mesada, bajo me...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-semi-amoblado-centrico-un-dormitorio-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/06/bfb9f212-d58e-44e4-9ff4-b5d60043b4fb.jpeg

10. Casa 3 Dormitorios dentro de los Bulevares - Alquiler — Consultar
   Ubicación: Reconquista
   Tipo: Casa / Dúplex
   4 ambientes, 3 dorm, 2 baños
   Casa dentro de los bulevares con las siguientes comodidades: P/B: estar/comedor con ventilador de techo; cocina con mesad...
   Link: https://jv-inmobiliaria.com/propiedades/casa/reconquista/casa-3-dormitorios-dentro-de-los-bulevares-alquiler-2/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/06/b0b5f543-fdcf-4df4-9df4-2e7d98615b45.jpeg

11. Casa 3 Dormitorios dentro de los Bulevares - Alquiler — $1.300.000 /por mes
   Ubicación: Reconquista
   Tipo: Casa / Dúplex
   4 ambientes, 3 dorm, 2 baños
   Casa dentro de los bulevares con las siguientes comodidades: P/B: cochera para dos autos; living comedor (con ventilador ...
   Link: https://jv-inmobiliaria.com/propiedades/casa/reconquista/casa-3-dormitorios-dentro-de-los-bulevares-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/06/793df9bd-668b-4b43-93fe-7179d931e8af.jpeg

12. Local Comercial en Villa Ocampo - Alquiler — $650.000 /por mes
   Ubicación: Villa Ocampo
   Tipo: Local
   1 ambientes, 1 baños
   Local comercial en Villa Ocampo con las siguientes comodidades: salón de 31,45 m2; baño; kitchen; frente vidriado. Sobre ...
   Link: https://jv-inmobiliaria.com/propiedades/local/villa-ocampo/local-comercial-en-villa-ocampo-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/06/c3723a8e-4f48-4bb9-a3b3-c9fbb835b5f0.jpeg

13. Local Comercial Céntrico en Villa Ocampo — $800.000 /por mes
   Ubicación: Villa Ocampo
   Tipo: Local
   1 ambientes, 1 baños
   Local comercial en Villa Ocampo con las siguientes comodidades: Salón amplio de 52 M2; baño; frente vidriado. Sobre calle...
   Link: https://jv-inmobiliaria.com/propiedades/local/villa-ocampo/local-comercial-centrico-en-villa-ocampo/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/06/c29d02ac-c688-44a3-b9b3-0198db790966.jpeg

14. Departamento Un Dormitorio dentro de los Bvs c/ Cochera - Alquiler — Consultar
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento dentro de los bulevares con las siguientes comodidades: un dormitorio en P/A; baño; P/B: cocina comedor con ...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-un-dormitorio-dentro-de-los-bvs-c-cochera-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/06/f6c389a7-644e-4cd8-a972-c7c881b82c69.jpeg

15. Dpto un Dormitorio dentro de los Bulevares - Alquiler — $450.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento dentro de los bulevares con las siguientes comodidades: un dormitorio; cocina comedor con mesada, bajo mesad...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-un-dormitorio-dentro-de-los-bulevares-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/05/6b7dd88a-ca03-4b42-8562-d1c5f18c45b7.jpeg

16. Dpto un Dormitorio dentro de los Bulevares - Alquiler — $280.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento dentro de los bulevares con las siguientes comodidades: un dormitorio; cocina comedor con mesada y bajo mesa...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/4440/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/05/ea359c83-3f83-4dad-a1c4-d67710e4980c.jpeg

17. Departamento un Dormitorio en barrio Obligado - Alquiler $260.000. — $260.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento en alquiler en barrio Obligado con las siguientes comodidades: un dormitorio; cocina comedor con mesada, baj...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-un-dormitorio-en-barrio-obligado-alquiler-260-000/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/05/ef055331-6f7e-4458-b4d2-9ce6ecaf5ee9.jpeg

18. Dpto 2 Dormitorios Céntrico semi amoblado - Alquiler — $590.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   3 ambientes, 2 dorm, 1 baños
   Departamento semi amoblado con las siguientes comodidades: dos dormitorios con placares (uno con A/A y el otro con ventil...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-2-dormitorios-centrico-semi-amoblado-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/05/e82505f9-11e6-466f-adf0-1ee64ea4bcec.jpeg

19. Local Comercial sobre calle Rossi — $400.000 /por mes
   Ubicación: Reconquista
   Tipo: Local
   1 ambientes, 1 baños
   Local comercial en esquina: ambiente de 40 m2 aproximados, baño, kitchen. Ventanas vidriadas y rejas. Sobre calle Rossi e...
   Link: https://jv-inmobiliaria.com/propiedades/local/reconquista/local-comercial-sobre-calle-rossi/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/05/a0b6cbac-5816-4c82-8a4a-5299dace2fd4.jpeg

20. Local Comercial en barrio Chapero - Alquiler — $350.000 /por mes
   Ubicación: Reconquista
   Tipo: Local
   2 ambientes, 1 baños
   Local comercial con las siguientes disposiciones: dos ambientes; frente vidriado y con rejas; baño. Mucha iluminación nat...
   Link: https://jv-inmobiliaria.com/propiedades/local/reconquista/local-comercial-en-barrio-chapero-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/05/c231a198-e7b8-4b3b-babd-e7d97f42cc1f-scaled.jpeg

21. Casa 3 Dormitorios Exclusiva Zona Residencial - Alquiler — $1.000.000 /por mes
   Ubicación: Reconquista
   Tipo: Casa / Dúplex
   4 ambientes, 3 dorm, 2 baños
   Casa en alquiler en exclusiva zona residencial con las siguientes comodidades: P/B: estar; living comedor; cocina amplia ...
   Link: https://jv-inmobiliaria.com/propiedades/casa/reconquista/casa-3-dormitorios-exclusiva-zona-residencial-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/04/4f0d2caf-cba0-4ae1-9c09-e217bd56e04d.jpeg

22. Dpto dentro de lo Bulevares Un Dormitorio - Precio $200.000! — $200.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento dentro de los bulevares con las siguientes comodidades: cocina comedor con mesada y bajo mesada; un dormitor...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-dentro-de-lo-bulevares-un-dormitorio-precio-300-000/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/03/3dcabdab-491c-4cf6-bc48-0e34998d8999.jpeg

23. Departamento Dos Dormitorios dentro de los Bulevares - Alquiler — $400.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 2 dorm, 1 baños
   Departamento dentro de los bulevares con las siguientes comodidades: dos dormitorios con ventilador de techo; cocina con ...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-un-dormitorio-dentro-de-los-bulevares-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/03/4aa2b71d-b155-4300-b8f3-df7117821ff7.jpeg

24. Departamento Amoblado Un Dormitorio barrio Nazareth - Alquiler — $550.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento en barrio Nazareth con las siguientes comodidades: un dormitorio con dos camas, placares, ventilador de tech...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/departamento-amoblado-un-dormitorio-barrio-nazareth-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/01/4050987d-6119-483d-8fdb-63b32e2b794d.jpeg

25. Dúplex 2 Dormitorios Exclusivo en barrio Chapero - Alquiler — $1.150.000 /por mes
   Ubicación: Reconquista
   Tipo: Casa / Dúplex
   3 ambientes, 2 dorm, 2 baños
   Dúplex en barrio Chapero que cuenta con las siguientes comodidades: P/B: cochera; living comedor amplio; baño; cocina con...
   Link: https://jv-inmobiliaria.com/propiedades/casa/reconquista/duplex-2-dormitorios-exclusivo-en-barrio-chapero-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2026/01/89eff1ad-0fbe-4ba2-97d8-7da35216d6fb.jpeg

26. Quinta Don Francisco - Alquiler por día!! — Consultar
   Ubicación: Reconquista
   Tipo: Casa Quinta
   4 ambientes, 2 dorm, 3 baños
   🏡QUINTA DON FRANCISCOUn lugar de encuentro 📍Zona Country La Rural, Rqta, Santa Fe. La casa tiene capacidad para ...
   Link: https://jv-inmobiliaria.com/propiedades/casa-quinta/reconquista/quinta-don-francisco-alquiler-por-dia/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2025/11/e79fd4d0-9fbc-48f3-a58c-35ce9fc1a4a1.jpeg

27. Dpto un Dormitorio barrio Chapero - Alquiler — $300.000 /por mes
   Ubicación: Reconquista
   Tipo: Departamento
   2 ambientes, 1 dorm, 1 baños
   Departamento en barrio Chapero con las siguientes comodidades: un dormitorio; cocina comedor con mesada y bajo mesada; ba...
   Link: https://jv-inmobiliaria.com/propiedades/departamento/reconquista/dpto-un-dormitorio-barrio-chapero-alquiler/
   Imagen: https://jv-inmobiliaria.com/wp-content/uploads/2025/11/IMG_3659-scaled.jpeg

`;
